package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("csar.ru")
    void generatedTest() {
        step("Open \"https://csat.ru\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Click on \"Login\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set username as \"Credo\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set passwd \"123123\"", () -> {
            step("// todo: just add selenium action");
        });

        step("verify that user was logged in", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://csat.ru'", () ->
            open("https://csat.ru"));

        step("Page title should have text 'Охранные системы безопасности в Санкт-Петербурге - компания Цезарь Сателлит'", () -> {
            String expectedTitle = "Охранные системы безопасности в Санкт-Петербурге - компания Цезарь Сателлит";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://csat.ru'", () ->
            open("https://csat.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}